<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="./?route=getAll">🡸 Catálogo</a></li>
  <li class="breadcrumb-item active">Detalles del Producto</li>
</ol>

<div class="container ">
    <div class="row mb-5">
        <div class="col-xl-7 mt-4">
            <img class="img-prod-desc" src="./app/assets/img/productos/<?php echo $one_product["imagen"]; ?>" alt="">
        </div>
        <div class="col-xl-5 mt-4">
            <h2 class=""><?php echo strtoupper($one_product["titulo"]); ?></h2>
            <div class="alert alert-dark tamaño" role="alert">
                Categoria: <?php echo strtoupper($one_product["categoria"]); ?>
            </div>
            <h3 class="mt-3">$ <?php echo strtoupper($one_product["precio"]); ?> ARS c/u</h3>
            <h4 class="mt-4">Descripción</h4>
            <div class="descripcion">
                <p><?php echo strtoupper($one_product["descripcion"]); ?></p>
            </div>
            <center class="mt-3">
                <a class="btn btn-primary" href="?route=car3&prod=<?php echo $one_product["id"]; ?>">Agregar al Carrito</a>
                <a class="btn btn-ligth" href="?route=getAll">Continuar Comprando</a>
            </center>
        </div>
        
    </div>
</div>


